// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Unchase.OData.ConnectedService.VS22
{
    internal sealed partial class Vsix
    {
        public const string Id = "Unchase.OData.ConnectedService.afc46f39-8c64-4e14-85d0-af6c7c4291f4";
        public const string Name = "Unchase OData Connected Service VS2022";
        public const string Description = @"OData V1-V4 connected service with extension methods for client-side proxy class.";
        public const string Language = "en-US";
        public const string Version = "1.5.0";
        public const string Author = "Unchase";
        public const string Tags = "OData, REST API, Code Generation, Scaffolding, Connected Service";
    }
}
